[package]
name = "riscv_cove_tap"
version = "0.2.0"
authors = ["Wojciech Ozga <woz@zurich.ibm.com>"]
description = "Library to parse the RISC-V CoVE's TEE attestation payload (TAP)"
edition = "2024"

[dependencies]
rand = {version = "0.10", default-features=false, optional=true, features=["thread_rng"] }

hybrid-array = {version = "0.4", default-features=false }
ml-kem = {version = "0.3", default-features=false }

# for symmetric encryption of payload
aes-gcm = {version="0.11", default-features = false, features=["aes", "alloc", "rand_core"]}

# provides macros that help removing boilerplate code in rust error handling
thiserror-no-std = "2.0"

[features]
parser = []
serializer = ["rand"]