[package]
name = "cove-tap-tool"
version = "0.1.0"
authors = ["Wojciech Ozga <woz@zurich.ibm.com>"]
description = "Tool to create TVM attestation payload for CoVE's confidential VM"
edition = "2021"

[dependencies]
clap = { version="4.6", features = ["derive"] } # for command line argument parsing
clap-num = {version = "1.2", default-features=false }
byteorder = {version = "1.5", default-features=false, features = ["std"] } # to serialize numbers using little/big endianness
rand = {version = "0.10", default-features=false, features = ["std"] }
sha3 = {version = "0.12", default-features=false } # to calculate integrity measurements of kernel, initramfs etc.
hybrid-array = {version = "0.4", default-features=false }
ml-kem = {version = "0.3", default-features=false }
aes-gcm = {version="0.11", features=["aes", "alloc", "rand_core"]}
riscv_cove_tap = {path="../../security-monitor/rust-crates/riscv_cove_tap", features=["parser", "serializer"]}

thiserror = "2.0"  # provides macros that help removing boilerplate code in the rust error handling
