# check: https://rust-lang.github.io/rustfmt/

max_width = 120
comment_width = 120
fn_call_width = 100

fn_params_layout = "Compressed"

hard_tabs = false

imports_granularity = "Module"
# use_small_heuristics = "Max"
wrap_comments = true

where_single_line = true

use_small_heuristics = "Max"

# report_todo = "Always"
# report_fixme = "Always"
# group_imports = "StdExternalCrate"
