name: ACE Build

on:
  push:
    branches: [ "main", "staging", "ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: install build dependencies
      run: sudo apt -qq -y install autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev
    - name: install OpenSBI dependencies
      run: sudo apt -qq -y install clang
    - name: install Qemu dependencies
      run: sudo apt -qq -y install git libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev ninja-build python3-venv libslirp-dev xz-utils
    - name: install Buildroot dependencies
      run: sudo apt -qq -y install unzip sed binutils diffutils build-essential bash patch gzip bzip2 perl tar cpio unzip rsync file bc findutils
    - name: install utilities
      run: sudo apt install -y sshpass
    - name: install rust
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: install rust nightly
      run: rustup default nightly
    - name: install rust nightly
      run: rustup target add riscv64gc-unknown-none-elf
    - name: install rust nightly
      run: rustup component add rustfmt
    - name: install cargo utils
      run: cargo install cargo-binutils
    - name: build riscv toolchain
      run: ACE_DIR=$(pwd)/build/ MAKEFLAGS="--silent -j4" make devtools
    - name: build emulator
      run: ACE_DIR=$(pwd)/build/ MAKEFLAGS="--silent -j4" make emulator
    - name: build tools
      run: ACE_DIR=$(pwd)/build/ MAKEFLAGS="--silent -j4" make tools
    - name: build hypervisor
      run: ACE_DIR=$(pwd)/build/ MAKEFLAGS="--silent -j4" make hypervisor
    - name: build firmware
      run: ACE_DIR=$(pwd)/build/ MAKEFLAGS="--silent -j4" make firmware
    - name: build confidential vms
      run: ACE_DIR=$(pwd)/build/ MAKEFLAGS="--silent -j4" make confidential_vms
    - name: run tests on confidential vms
      run: ACE_DIR=$(pwd)/build/ PATH=$PATH:$(pwd)/build/tools ace test
