name: ACE Build

on:
  push:
    branches: [ "main", "staging", "ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: install build dependencies
      run: sudo apt-get update -y && sudo apt-get -qq -y install autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev
    - name: install OpenSBI dependencies
      run: sudo apt-get update -y && sudo apt-get -qq -y install clang
    - name: install Qemu dependencies
      run: sudo apt-get update -y && sudo apt-get -qq -y install git libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev ninja-build python3-venv libslirp-dev xz-utils
    - name: install Buildroot dependencies
      run: sudo apt-get update -y && sudo apt-get -qq -y install unzip sed binutils diffutils build-essential bash patch gzip bzip2 perl tar cpio unzip rsync file bc findutils
    - name: install utilities
      run: sudo apt-get update -y && sudo apt-get -qq install -y sshpass
    - name: install rust
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: install rust nightly
      run: rustup default nightly
    - name: install rust nightly
      run: rustup target add riscv64gc-unknown-none-elf
    - name: install rust nightly
      run: rustup component add rustfmt
    - name: build riscv toolchain
      run: ACE_DIR=$(pwd)/build/ make --silent -j8 devtools
    - name: build emulator
      run: ACE_DIR=$(pwd)/build/ make --silent -j8 emulator
    - name: build tools
      run: ACE_DIR=$(pwd)/build/ make --silent -j8 tools
    - name: build hypervisor
      run: ACE_DIR=$(pwd)/build/ make --silent -j8 hypervisor
    - name: build firmware
      run: ACE_DIR=$(pwd)/build/ make --silent -j8 firmware
    - name: build confidential vms
      run: ACE_DIR=$(pwd)/build/ make --silent -j8 confidential_vms
    - name: rebuild all to include changes to cvm disk
      run: ACE_DIR=$(pwd)/build/ make --silent -j8
    - name: run tests on confidential vms
      run: ACE_DIR=$(pwd)/build/ PATH=$PATH:$(pwd)/build/tools ace test
